### ISSUE TITLE
node-gyp fails on npm install phidget

### ISSUE THREAD

**Issue by anthonyringoet** [thisandagain/phidget#1]
The install fails every time. It's something with node-gyp. Any idea's about this?
Tried with node v10.0.0 and v10.0.23

```
$ npm install phidget --save-dev
npm WARN package.json dummy-printer@0.0.0 No repository field.
npm WARN package.json dummy-printer@0.0.0 No README data
npm http GET https://registry.npmjs.org/phidget
npm http 304 https://registry.npmjs.org/phidget

> phidget@0.1.0 install /Users/anthony/Desktop/dummy/node_modules/phidget
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
  CXX(target) Release/obj.target/binding/src/servo.o
../src/servo.cc:3:10: fatal error: 'phidget21.h' file not found
#include <phidget21.h>
         ^
1 error generated.
make: *** [Release/obj.target/binding/src/servo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/anthony/.nvm/v0.10.23/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/Users/anthony/.nvm/v0.10.23/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/anthony/Desktop/dummy/node_modules/phidget
gyp ERR! node -v v0.10.23
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! phidget@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phidget@0.1.0 install script.
npm ERR! This is most likely a problem with the phidget package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls phidget
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/anthony/.nvm/v0.10.23/bin/node" "/Users/anthony/.nvm/v0.10.23/bin/npm" "install" "phidget" "--save-dev"
npm ERR! cwd /Users/anthony/Desktop/dummy
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/anthony/Desktop/dummy/npm-debug.log
npm ERR! not ok code 0
```

**Comment by thisandagain** [comment]
Looks like the phidget driver isn't installed. Can you confirm that you installed the drivers from http://www.phidgets.com/docs/Operating_System_Support

**Comment by anthonyringoet** [comment]
I installed those yes. I'm on Mac OS 10.9.
The phidget preference pane was visible in system preferences.

**Comment by laurlaur** [comment]
I have the same problem. what was the fix for that? Using Windows 7.

..\src\servo.cc(3): Error c1083: cannot open include file: 'phidget21.h': No such file or directory [c:\users....

I have the drivers installed and I can read measurements off the phidget board in C code that I created with no problem. I have fiddled around trying it to get to recognise the drivers but no luck. 

Thanks!

**Comment by anthonyringoet** [comment]
@laurlaur I did not find a fix

**Comment by thisandagain** [comment]
Sorry for the delay on this folks. Looks like an issue with the latest version(s) of `gyp` and the C++ bindings.

**Comment by dimitry** [comment]
Just checking in. Any updates on this? I'm on Mac OS 10.10 and getting the same error even though Phidgets is definitely working from Sys Prefs. Thank you.
